# ==============================================================================
# MRB Analysis Script 14: Compile Manuscript Statistics for Code Review
# ==============================================================================
# Purpose: Create a comprehensive, well-formatted table of ALL statistical tests
#          reported in the manuscript to facilitate code review and cross-referencing.
#
# This script:
#   1. Loads the statistical comparison table (from scripts 6-8 outputs)
#   2. Formats results for easy reading and manuscript cross-referencing
#   3. Exports as both CSV (machine-readable) and HTML (human-readable)
#   4. Provides summary statistics and key findings
#
# Inputs:
#   - output/MRB/MANUSCRIPT_STATS_TABLE.csv           # Statistical comparison table
#   - output/MRB/STATISTICAL_TESTS_COMPARISON.md      # Detailed test descriptions
#
# Outputs:
#   - output/MRB/tables/MANUSCRIPT_STATISTICAL_TESTS.csv   # All tests (CSV)
#   - output/MRB/tables/MANUSCRIPT_STATISTICAL_TESTS.html  # Formatted table (HTML)
#
# ==============================================================================

# Source centralized libraries, utilities, and figure standards
source("scripts/MRB/1.libraries.R")
source("scripts/MRB/utils.R")
source("scripts/MRB/mrb_figure_standards.R")

# All packages loaded via source("scripts/MRB/1.libraries.R") above

# Create output directory
table_dir <- here("output/MRB/tables")
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)

cli::cli_rule("Compiling Manuscript Statistics for Code Review")
cat("\n")

# ==============================================================================
# LOAD STATISTICAL COMPARISON TABLE
# ==============================================================================

cli::cli_h2("Loading statistical comparison table")

# This table was generated by comparing old vs new analysis results
# and contains all statistical tests from scripts 6, 7, and 8
stats_raw <- read_csv(here("output/MRB/MANUSCRIPT_STATS_TABLE.csv"),
                      show_col_types = FALSE)

cli::cli_alert_success("Loaded {nrow(stats_raw)} statistical tests")

# Refresh rows that are regenerated by the active Script 8 pipeline. The
# MANUSCRIPT_STATS_TABLE.csv source is a revision-era ledger, so these in-memory
# updates keep the submission-facing compiled table from preserving stale p-values.
update_stat_row <- function(stats, description, test_statistic = NULL, df = NULL,
                            p_value = NULL, effect_size = NULL, notes = NULL) {
  idx <- stats$`Test Description` == description
  if (!any(idx)) return(stats)
  if (!is.null(test_statistic)) stats$`New Test Statistic`[idx] <- test_statistic
  if (!is.null(df)) stats$`New df`[idx] <- df
  if (!is.null(p_value)) stats$`New p-value`[idx] <- p_value
  if (!is.null(effect_size)) stats$`New Effect Size`[idx] <- effect_size
  if (!is.null(notes)) stats$Notes[idx] <- notes
  stats
}

comm_summary_path <- here("output/MRB/tables/LMM_COMM_vs_COND_summary.csv")
if (file.exists(comm_summary_path)) {
  comm_summary <- readr::read_csv(comm_summary_path, show_col_types = FALSE)
  matrix_labels <- c("SQRT_CS", "HELLINGER", "SQRT")
  for (matrix_label in matrix_labels) {
    this_row <- comm_summary |>
      dplyr::filter(.data$Matrix == matrix_label) |>
      dplyr::slice(1)
    if (nrow(this_row) == 1L) {
      stats_raw <- update_stat_row(
        stats_raw,
        paste("Community vs Condition:", matrix_label),
        test_statistic = sprintf("t=%.3f", this_row$t_stat),
        df = sprintf("%.2f", this_row$DF),
        p_value = this_row$p_value,
        effect_size = sprintf(
          "beta=%.3f; 95%% CI [%.3f, %.3f]",
          this_row$Estimate, this_row$CI_lower, this_row$CI_upper
        ),
        notes = paste(
          "Current Script 8 fixed-effect summary from LMM_COMM_vs_COND_summary.csv;",
          "p-value from lmerTest denominator df."
        )
      )
    }
  }
}

stats_raw <- update_stat_row(
  stats_raw,
  "Mantel: Community-Condition distance",
  test_statistic = NA_character_,
  df = NA_character_,
  p_value = NA_character_,
  effect_size = NA_character_,
  notes = "Not part of the current canonical Script 8 output; retain only if regenerated and reported explicitly."
)

stats_raw <- update_stat_row(
  stats_raw,
  "Volume ANCOVA - Interaction",
  notes = paste(
    "Type III interaction term in the full model.",
    "For manuscript interpretation, pair this with the interaction-vs-parallel LRT",
    "(p=0.073) and non-significant pairwise slope contrasts."
  )
)

# ==============================================================================
# CLEAN AND FORMAT THE TABLE
# ==============================================================================

cli::cli_h2("Formatting results table")

manuscript_stats <- stats_raw %>%
  # Focus on NEW results (current analysis)
  dplyr::select(Analysis, `Test Description`, `Model/Method`,
                test_statistic = `New Test Statistic`,
                df = `New df`,
                p_value = `New p-value`,
                effect_size = `New Effect Size`,
                Impact, Notes) %>%

  # Convert p_value to numeric (may be stored as character)
  dplyr::mutate(
    p_value = as.numeric(p_value),
    df = as.numeric(df)
  ) %>%

  # Add row numbers for easy reference
  dplyr::mutate(test_id = dplyr::row_number()) %>%

  # Clean up analysis categories
  dplyr::mutate(
    section = dplyr::case_when(
      stringr::str_detect(Analysis, "Coral Growth") ~ "Coral Growth",
      stringr::str_detect(Analysis, "Coral Physiology") ~ "Coral Physiology",
      stringr::str_detect(Analysis, "CAFI") ~ "CAFI-Coral Community",
      TRUE ~ Analysis
    )
  ) %>%

  # Add significance markers
  dplyr::mutate(
    significance = dplyr::case_when(
      is.na(p_value) ~ "—",
      p_value < 0.001 ~ "***",
      p_value < 0.01 ~ "**",
      p_value < 0.05 ~ "*",
      p_value < 0.1 ~ ".",
      TRUE ~ "NS"
    ),
    p_formatted = dplyr::case_when(
      is.na(p_value) ~ "—",
      p_value < 0.001 ~ "< 0.001",
      TRUE ~ sprintf("%.3f", p_value)
    )
  ) %>%

  # Add manuscript location hints
  dplyr::mutate(
    manuscript_location = dplyr::case_when(
      Impact == "PRIMARY" ~ "Results (Main findings)",
      Impact == "NEW" & p_value < 0.05 ~ "Results or Supplement",
      Impact == "INDIRECT" & p_value < 0.05 ~ "Results or Supplement",
      Impact == "UNCHANGED" ~ "Results",
      TRUE ~ "Methods or Supplement"
    )
  ) %>%

  # Reorder columns for clarity
  dplyr::select(test_id, section, Analysis, `Test Description`, `Model/Method`,
                test_statistic, df, p_value, p_formatted, significance,
                effect_size, Impact, manuscript_location, Notes)

# ==============================================================================
# EXPORT TABLES
# ==============================================================================

cli::cli_h2("Exporting results tables")

# 1. CSV format (for easy import/inspection)
write_csv(manuscript_stats,
          file.path(table_dir, "MANUSCRIPT_STATISTICAL_TESTS.csv"))
cli::cli_alert_success("Saved: MANUSCRIPT_STATISTICAL_TESTS.csv")

# 2. HTML table with nice formatting
stats_html <- manuscript_stats %>%
  dplyr::select(test_id, section, Analysis, test_statistic, df,
                p_value, p_formatted, significance, Impact, manuscript_location, Notes) %>%
  gt(id = "manuscript_statistical_tests") %>%
  tab_header(
    title = "Complete Statistical Tests for Manuscript",
    subtitle = paste0("Generated: ", Sys.Date(), " | Scripts 6-8 | n = 44 corals")
  ) %>%
  cols_label(
    test_id = "ID",
    section = "Section",
    Analysis = "Analysis",
    test_statistic = "Test Statistic",
    df = "df",
    p_value = "p (numeric)",
    p_formatted = "p-value",
    significance = "Sig.",
    Impact = "Impact",
    manuscript_location = "Manuscript Location",
    Notes = "Notes"
  ) %>%
  cols_hide(columns = c(p_value)) %>%  # Hide numeric p_value column (used for styling only)
  tab_style(
    style = cell_fill(color = "lightyellow"),
    locations = cells_body(rows = p_value < 0.05 & !is.na(p_value))
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(
      columns = significance,
      rows = significance %in% c("*", "**", "***")
    )
  ) %>%
  tab_style(
    style = cell_fill(color = "lightblue"),
    locations = cells_body(
      rows = Impact == "PRIMARY"
    )
  ) %>%
  tab_footnote(
    footnote = "Significance: *** p<0.001, ** p<0.01, * p<0.05, . p<0.1, NS p≥0.1"
  ) %>%
  tab_footnote(
    footnote = "Blue highlighting = PRIMARY results (main findings)"
  ) %>%
  tab_footnote(
    footnote = "Yellow highlighting = Significant results (p<0.05)"
  ) %>%
  tab_options(
    table.font.size = px(12),
    heading.title.font.size = px(18),
    heading.subtitle.font.size = px(14)
  )

# Save HTML
gtsave(stats_html,
       file.path(table_dir, "MANUSCRIPT_STATISTICAL_TESTS.html"))
cli::cli_alert_success("Saved: MANUSCRIPT_STATISTICAL_TESTS.html")

# ==============================================================================
# SUMMARY STATISTICS
# ==============================================================================

cli::cli_h2("Summary Statistics")

cat("\n")
cli::cli_alert_info("Total tests documented: {nrow(manuscript_stats)}")

# Count by section
section_counts <- manuscript_stats %>%
  dplyr::count(section) %>%
  dplyr::arrange(dplyr::desc(n))

cat("\nTests by section:\n")
for (i in 1:nrow(section_counts)) {
  cli::cli_alert_info("  {section_counts$section[i]}: {section_counts$n[i]} tests")
}

# Significant results
sig_tests <- manuscript_stats %>%
  dplyr::filter(p_value < 0.05, !is.na(p_value))

cli::cli_alert_success("\nSignificant tests (p < 0.05): {nrow(sig_tests)} of {sum(!is.na(manuscript_stats$p_value))}")

# Primary findings
primary_tests <- manuscript_stats %>%
  dplyr::filter(Impact == "PRIMARY")

cli::cli_alert_info("Primary findings: {nrow(primary_tests)} tests")

cat("\n")
cli::cli_h3("Key Primary Findings:")
cat("\n")

primary_summary <- primary_tests %>%
  dplyr::select(Analysis, test_statistic, p_formatted, significance) %>%
  dplyr::mutate(result = paste0(test_statistic, ", p=", p_formatted, " ", significance))

for (i in 1:nrow(primary_summary)) {
  cli::cli_alert("  {primary_summary$Analysis[i]}: {primary_summary$result[i]}")
}

cat("\n")
cli::cli_h3("Significant findings (p < 0.05):")
cat("\n")

sig_summary <- sig_tests %>%
  dplyr::select(section, Analysis, p_formatted) %>%
  dplyr::arrange(section, Analysis)

print(sig_summary, n = Inf)

# ==============================================================================
# REPRODUCIBILITY NOTE
# ==============================================================================

cat("\n")
cli::cli_rule("Reproducibility Information")
cat("\n")

cli::cli_alert_info("These statistics were generated by:")
cli::cli_alert("  1. scripts/MRB/6.coral-growth.R (Coral growth analyses)")
cli::cli_alert("  2. scripts/MRB/7.coral-physiology.R (Physiology analyses)")
cli::cli_alert("  3. scripts/MRB/8.coral-caffi.R (Community analyses)")

cat("\n")
cli::cli_alert_info("To fully reproduce these results from raw data, run:")
cli::cli_alert("  Rscript scripts/MRB/6.coral-growth.R")
cli::cli_alert("  Rscript scripts/MRB/7.coral-physiology.R")
cli::cli_alert("  Rscript scripts/MRB/8.coral-caffi.R")

cat("\n")
cli::cli_alert_success("✓ All statistics compiled for code review!")
cli::cli_alert_info("Tables saved to: {table_dir}")

cat("\n")
cli::cli_rule("End of Script 14")
